### PR TITLE
howto secrets

### PR DESCRIPTION
**Pull request by willr3**
- revert to schema.json
- replace depricated methods and fix warnings
- add timeout for CI issues
- fix set-signal incrementing expected signal count and move docs
- How to upload files in a qDup script
- How to pass secrets into qDup

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Borderline reference...

**Comment by willr3** [comment]
Yes, The information in some of the `How to` are basically a reference to why the command exists but we wanted to include a few short "How to do X" that may answer questions people have rather than relying on them to discover the content in the reference.

**Comment by willr3** [comment]
I agree, a lot of the How to topics appear to be rather straight forward usage of the commands. I think that it might help new users who come to qDup with what they want to accomplish. They may find the task mentioned in a How To but may not know to look for the command name references.

**Comment by johnaohara** [comment]
LGTM

**Review by johnaohara — APPROVED** [review]

**Pull request merged**
