### PR TITLE
Add methods to context API to allow commnds to create new temporary s…

### PR DESCRIPTION
**Pull request by johnaohara**
…cratch files/dirs for commands to process local data

### CODE REVIEW

**Comment by willr3** [comment]
We considered and decided against this in the past. `TEMP_DIR` and `MAKE_TEMP_CMD` static variables are left over from when we first looked at adding this:
https://github.com/Hyperfoil/qDup/blob/master/src/main/java/io/hyperfoil/tools/qdup/config/RunConfigBuilder.java#L59
We decided against qDup automatically creating anything on the remote host in part because it opened qDup up to having to manage the directory in failure cases. If this is for using qDup as a library then perhaps we can find a way to expose the option for the library user to make the folder when starting the remote sessions.

**Comment by johnaohara** [comment]
The intention was not to create a dir on the remote host, but on the machine running the qDup process. It was intended to be created alongside the /tmp/qdupXXX directory that the run.json etc is stored in, but not to pollute the output dir.  If you think that is an acceptable use case, I can revisit this to ensure the dir isn't being created on the remote machine

**Comment by johnaohara** [comment]
The alternative is that I call `context.getRunOutputPath()` and use the output dir as the temp file scratch area

**Comment by johnaohara** [comment]
After discussing this, I will close this PR down and handle tmp dir creation in the tools importing qDup instead

**Pull request closed without merging**
